Zero.Mvc.Manage/Controllers/Cates/CateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;

using Zero.Core.Web;
using Zero.Core.Pattern;
using Zero.Domain.Cates;
using Zero.Service.Cates;

namespace Zero.Mvc.Manage.Controllers.Cates
{
    public class CateController : BaseController
    {
        CateService _cateService;

        public CateController()
        {
            _cateService = Singleton<CateService>.GetInstance();
        }

        public ActionResult CateIndex()
        {
            return View();
        }

        public ActionResult CateList()
        {
            Func<List<Cate>, dynamic> getJson = null;
            getJson = (List) =>
            {
                return List.Select(c => new
                {
                    id = c.CateId,
                    text = c.CateName,
                    ChildCount = c.ChildCount,
                    CreateTiem = c.CreateTime,
                    UpdateTime = c.UpdateTime,
                    children = c.children == null ? null : getJson(c.children)
                });
            };

            List<Cate> cateList = _cateService.GetList(0, 0);
            cateList = _cateService.ConvertCateListToTree(cateList);
            return Json(getJson(cateList), JsonRequestBehavior.AllowGet);
        }

        public ActionResult CateDropList()
        {
            Func<List<Cate>, dynamic> getJson = null;
            getJson = (List) =>
            {
                return List.Select(c => new
                {
                    id = c.CateId,
                    text = c.CateName,
                    ChildCount = c.ChildCount,
                    CreateTiem = c.CreateTime,
                    UpdateTime = c.UpdateTime,
                    children = c.children == null ? null : getJson(c.children)
                });
            };

            List<Cate> cateList = _cateService.GetList(0, 0);
            cateList = _cateService.ConvertCateListToTree(cateList);
            cateList.Insert(0, new Cate() { CateId = 0, CateName = "请选择" });
            return Json(getJson(cateList), JsonRequestBehavior.AllowGet);
        }

        public ActionResult CateAdd()
        {
            int cateId = RequestHelper.QueryInt("cateId");

            if (cateId > 0)
            {
                Cate cate = _cateService.GetById(cateId);
                cateId = cate != null ? cateId : 0;
            }

            ViewBag.Pid = cateId;

            return View();
        }

        [HttpPost]
        public ActionResult CateAdd(Cate cate)
        {
            ResultInfo resultInfo = new ResultInfo(1, "验证不通过");

            if (ModelState.IsValid)
            {
                resultInfo = _cateService.Add(cate);
            }

            return Json(resultInfo);
        }

        public ActionResult CateEdit()
        {
            int cateId = RequestHelper.QueryInt("cateId");
            Cate cate=_cateService.GetById(cateId);
            return View(cate);
        }

        [HttpPost]
        public ActionResult CateEdit(Cate cate)
        {
            ResultInfo resultInfo = new ResultInfo(1, "验证不通过");

            if (ModelState.IsValid)
            {
                Cate oldCate = _cateService.GetById(cate.CateId);

                if (oldCate == null)
                {
                    resultInfo = new ResultInfo(1, "该信息已被删除或不存在，请刷新列表！");
                    return Json(resultInfo);
                }

                int oldPid = oldCate.Pid;
                oldCate.CateId = cate.CateId;
                oldCate.CateName = cate.CateName;
                oldCate.Pid = cate.Pid;

                resultInfo = _cateService.Update(oldCate, oldPid);
            }

            return Json(resultInfo);
        }

        [HttpPost]
        public ActionResult CateOperate()
        {
            ResultInfo resultInfo;

            string action = RequestHelper.All("action").ToLower();
            string ids = RequestHelper.All("ids").ToLower();

            if (action == "")
            {
                resultInfo = new ResultInfo((int)ResultStatus.Error, "未选择任何操作！");
                return Json(resultInfo);
            }

            if (ids == "")
            {
                resultInfo = new ResultInfo((int)ResultStatus.Error, "未选择任何操作项！");
                return Json(resultInfo);
            }

            switch (action)
            {
                case "delete":
                    _cateService.Delete(Utils.StrToInt(ids));
                    break;
            }

            return Json(new ResultInfo("操作成功"));
        }

        public ActionResult CateAttrIndex()
        {
            return View();
        }
    }
}

Zero.Mvc.Manage/Controllers/Customs/CustomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Zero.Mvc.Manage.Models;
using Zero.Core.Web;
using Zero.Domain.Customs;
using Zero.Service.Customs;

namespace Zero.Mvc.Manage.Controllers.Customs
{
    public class CustomController : Controller
    {
        public ICustomService _customService;

        public CustomController(ICustomService customService)
        {
            _customService = customService;
        }

        public ActionResult CustomList()
        {
            int pageIndex = RequestHelper.QueryInt("page");
            int pageSize = RequestHelper.QueryInt("rows");

            pageIndex = pageIndex <= 0 ? 0 : pageIndex - 1;
            if (pageSize <= 0) pageSize = 10;

            IPage<Custom> newsItemPage = _customService.GetList(pageIndex, pageSize);

            return Json(newsItemPage, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CustomIndex()
        {
            return View();
        }


        public ActionResult CustomAdd()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CustomAdd(CustomModel customModel)
        {
            ResultInfo resultInfo = new ResultInfo(1, "验证不通过");

            if (ModelState.IsValid)
            {
                customModel.Custom.Sql = _customService.GetProductSql(customModel.Custom.Quantity,customModel.ProductSearch);
                resultInfo = _customService.Add(customModel.Custom);
            }

            return Json(resultInfo);
        }

        public ActionResult CustomEdit()
        {
            int customId = RequestHelper.QueryInt("customId");
            Custom custom = _customService.GetById(customId);
            return View(custom);
        }


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CustomEdit(Custom custom)
        {
            ResultInfo resultInfo = new ResultInfo(1, "验证不通过");

            if (ModelState.IsValid)
            {
                Custom oldCustomItem = _customService.GetById(custom.CustomId);

                if (oldCustomItem == null)
                {
                    return Json(new ResultInfo(1, "该信息已被删除或不存在，请刷新列表！"));
                }

                oldCustomItem = custom;

                resultInfo = _customService.Edit(custom);
            }

            return Json(resultInfo);
        }

    }
}

Zero.Mvc.Manage/Views/Custom/CustomAdd.cshtml
@{
    Layout = "~/Views/Shared/Tab/_Add.cshtml";
    ViewBag.Title = "CustomAdd";
}

<form id="Form" action="@Url.Action("CustomAdd","Custom")" method="post">
    <div id="tt" class="easyui-tabs" data-options="tabPosition:'top'">
    
    <div title="自定义列表添加">
    <table class="z-tb-form">
        <tr>
            <th>标题：</th>
            <td>
               <input type="text" name="Title"  data-options="required:true,validType:['length[2,30]']" class="easyui-validatebox"  style="width:500px;">
            </td>
        </tr>
        <tr>
            <th>条数：</th>
            <td>
               <input type="text" name="Amount" data-options="required:true,validType:['number','size[0,500]']" class="easyui-validatebox"  style="width:100px;"/>
            </td>
        </tr>
        <tr>
            <th>类型：</th>
            <td>
                <input type="radio" id="SearchType" name="CustomType" checked/><label for="SearchType">检索</label>
                <input type="radio" id="SelectType" name="CustomType"/><label for="SelectType">筛选</label>
            </td>
        </tr>
        <tr>
            <th>条件：</th>
            <td>
               <div style="border:1px solid #95B8E7;width:480px;padding:10px;">
                   <table id="SearchForm" class="z-tb-form">
                       <tr>
                            <th>类别：</th>
                            <td><input type="text" id="CateId" name="CateId" data-options="url:'@Url.Action("CateList","Cate")'" class="easyui-combotree"  style="width:200px;"></td>
                        </tr>
                        <tr>
                            <th>标题：</th>
                            <td>
                               <input type="text" id="Keyword" name="Keyword" data-options="required:true,validType:['length[2,30]']"  style="width:300px;">
                            </td>
                        </tr>
                    </table>

                    <table id="SelectForm" class="z-tb-form">
                        <tr>
                            <th>请选择：</th>
                            <td>
                               <ul>
                                   <li>商品123</li>
                                   <li>商品123</li>
                                   <li>商品123</li>
                                   <li>商品123</li>
                                   <li>商品123</li>
                                   <li>商品123</li>
                                   <li>商品123</li>
                               </ul>
                            </td>
                            <td>
                                <p>添加</p>
                                <p>移除</p>
                                <p>清空</p>
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>
    </div>

    </div>
    <script>
        $(function () {
            $("#SearchType").click(function () {
                $("#SearchForm").removeClass("hidden");
                $("#SelectForm").addClass("hidden");
            });
            $("#SelectType").click(function () {
                $("#SearchForm").addClass("hidden");
                $("#SelectForm").removeClass("hidden");
            });
        });


        

    </script>
</form>

Zero.Mvc.Manage/Views/Custom/CustomEdit.cshtml
@{
    ViewBag.Title = "CustomEdit";
}

<h2>CustomEdit</h2>

Zero.Mvc.Manage/Views/Custom/CustomIndex.cshtml
@{
    Layout = "~/Views/Shared/Tab/_Index.cshtml";
    ViewBag.Title = "CustomIndex";
}

<!-- 列表 -->
<table id="grid"></table>

<!-- 工具栏 -->
<div id="toolbar">
    <div>
        <a href="#" id="add"  class="easyui-linkbutton" iconCls="icon-add" plain="true">添加</a>
        <a href="#" id="edit" class="easyui-linkbutton" iconCls="icon-edit" plain="true">修改</a>
        <a href="#" id="remove" class="easyui-linkbutton" iconCls="icon-remove" plain="true">移除</a>
        <a href="#" id="reload" class="easyui-linkbutton" iconCls="icon-reload" plain="true">刷新</a>
        
    </div>
   @* <div>
        Date From: <input class="easyui-datebox" style="width:80px">
        To: <input class="easyui-datebox" style="width:80px">
        Language: 
        <select class="easyui-combobox" panelHeight="auto" style="width:100px">
            <option value="java">Java</option>
            <option value="c">C</option>
            <option value="basic">Basic</option>
            <option value="perl">Perl</option>
            <option value="python">Python</option>
        </select>
        <a href="#" class="easyui-linkbutton" iconCls="icon-search">Search</a>
    </div>*@
</div>

<script type="text/javascript">

    var controller = "Custom";
    var controllerName = "自定义列表";

    $(function () {

        //加载网格(搜索中文版对照属性，来配置)
        $('#grid').datagrid({
            title: '自定义列表',
            collapsible: true,
            rownumbers: true,
            url: '/Custom/CustomList',
            method: 'get',
            loadMsg: '正在加载数据...',
            //idField: 'ProductId',
            fitColumns: false,
            width: 1180,
            height: 630,
            pagination: true,
            pageSize: 30,
            pageList: [10, 20, 30, 40, 50, 100],
            frozenColumns: [[
                { field: 'CustomId', checkbox: true },
                //{ field: 'ProductId', title: '商品编号', width: 50, algin: 'center' },//会绑定checkbox
                { field: 'id', title: '编号', width: 60, align: 'center' },
                { field: 'Title', title: '标题', width: 140,algin: 'center'},
            ]],
            columns: [[
                { field: 'operate', title: '操作', width: 80, align: 'center', formatter: operateFormat },
            ]],
            onLoadError: function () {
                $.messager.alert('提醒', '数据加载错误，请重试或重新登入系统');
            },
            toolbar: '#toolbar',

            //openParentTab('商品添加部分', '/Product/ProductAddPart');
        });

        function operateFormat(value, row, index) {
            var html = "";
            html += openParentTabLinkButton('修改', '/Custom/CustomEdit?CustomId=' + row.id, row.id);
            html += " | ";
            html += "<a href=\"javascript:void(0);\" onclick=\"operateAjax({ action: 'delete', ids:" + row.id + " })\">删除</a>";
            return html;
        }
    });
</script>